development:
  adapter: postgresql
  encoding: unicode
  database: heig-survey16_dev
  host: 127.0.0.1
  pool: 5
  username: adrienbigler
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: heig-survey16_test
  host: 127.0.0.1
  pool: 5
  username: adrienbigler
  password: 