development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME_DEV'] %>
  host: 127.0.0.1
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME_TEST'] %>
  host: 127.0.0.1
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>  